
name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install tools
      run: cd tests && make install-all
    - name: Format check
      run: cd tests && make check-code-format
    - name: Build contract
      run: make all-via-docker
    - name: Run all testcases
      run: cd tests && make all
    - name: Run ckb-auth-cli tests
      run: cd tools/ckb-auth-cli && cargo test

